#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/plazafyi/plaza-go,github.com/stainless-sdks/plaza-go"

REPLACEMENT="${1:-"../plaza-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/plazafyi/plaza-go="$REPLACEMENT"
go mod tidy -e
